// flow-typed signature: eb1e2c3225f859ef74c419f025bbe5e5
// flow-typed version: <<STUB>>/cartesian-product_v2.1.2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cartesian-product'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cartesian-product' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cartesian-product/lib/product' {
  declare module.exports: any;
}

declare module 'cartesian-product/test/helpers/chai' {
  declare module.exports: any;
}

declare module 'cartesian-product/test/spec/product.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cartesian-product/lib/product.js' {
  declare module.exports: $Exports<'cartesian-product/lib/product'>;
}
declare module 'cartesian-product/test/helpers/chai.js' {
  declare module.exports: $Exports<'cartesian-product/test/helpers/chai'>;
}
declare module 'cartesian-product/test/spec/product.spec.js' {
  declare module.exports: $Exports<'cartesian-product/test/spec/product.spec'>;
}
