// flow-typed signature: 997df4ad8d15c30c9c20456219c23976
// flow-typed version: <<STUB>>/find-cache-dir_v1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'find-cache-dir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'find-cache-dir' {
  declare module.exports: any;
}
