// flow-typed signature: a5399fae6c35c57a11fc45c54857b7e7
// flow-typed version: <<STUB>>/sharp_v0.20.2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sharp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sharp' {
  declare export type Meta = {
    width: number,
    height: number,
    format: string,
    hasAlpha: boolean,
  };

  declare export class Image {
    blur(): Image;
    resize(): Image;
    max(): Image;
    min(): Image;
    crop(): Image;
    toFormat(): Image;
    clone(): Image;
    metadata(): Promise<Meta>;
    toBuffer((err: ?Error, image: Buffer, meta: *) => void): void;
  }

  declare export default (Buffer) => Image;
}
